name: SwiftModule
description: Swift Packageに新しいモジュールを追加するテンプレート

macros:
  - name: ___MODULE_NAME___
    description: "モジュール名"
    type: string
    validate: "^[A-Z][a-zA-Z0-9]*$"

  - name: ___PACKAGE_PATH___
    description: "Swift Packageのパス"
    type: path

  - name: ___MODULE_TYPE___
    description: "モジュールタイプ"
    type: choice
    choices:
      - library
      - executable
    default: library

  - name: ___MODULE_DEPENDENCIES___
    description: "モジュールの依存関係 (カンマ区切りで指定)"
    type: array 
    format: $elements.join(" ")

  - name: ___CREATE_TESTS___
    description: "テストファイルを作成しますか？"
    type: boolean
    default: true

pre_hatch:
  - id: change-module-dependencies-format
    run: |
      set -e
      if [[ -z "___MODULE_DEPENDENCIES___" ]]; then
        js_array='[]'
      else
        IFS=',' read -ra items <<< "___MODULE_DEPENDENCIES___"
        js_array='['
        for i in "${!items[@]}"; do
          js_array+="\"${items[i]}\""
          [[ $i -lt $((${#items[@]} - 1)) ]] && js_array+=', '
        done
        js_array+=']'
      fi

      echo "module-dependencies-array=$js_array"
  - if: ${{ pre_hatch.change-module-dependencies-format.outputs.module-dependencies-array }}.length == 0
    run: |
      set -e
      xcrun swift package --package-path ___PACKAGE_PATH___ add-target ___MODULE_NAME___ --type ___MODULE_TYPE___

  - if: ${{ pre_hatch.change-module-dependencies-format.outputs.module-dependencies-array }}.length > 0
    run: |
      set -e
      xcrun swift package --package-path ___PACKAGE_PATH___ add-target ___MODULE_NAME___ --type ___MODULE_TYPE___ --dependencies ___MODULE_DEPENDENCIES___

  - run: |
      rm -f ___PACKAGE_PATH___/Sources/___MODULE_NAME___/___MODULE_NAME___.swift

  - if: ___CREATE_TESTS___
    run: |
      set -e
      xcrun swift package --package-path ___PACKAGE_PATH___ add-target ___MODULE_NAME___Tests --type test --dependencies ___MODULE_NAME___
      rm -f ___PACKAGE_PATH___/Tests/___MODULE_NAME___Tests/___MODULE_NAME___Tests.swift

hatch:
  output: ___PACKAGE_PATH___

  exclude:
    - "*.md"
    - ".DS_Store"
    - "config.yml"

    - if: ___CREATE_TESTS___ === false
      paths:
        - "___MODULE_NAME___Tests.swift"

    - if: "___MODULE_TYPE___ !== 'executable'"
      paths:
        - "main.swift"

post_hatch:
  - run: |
      set -e
      mv ___MODULE_NAME___.swift ___PACKAGE_PATH___/Sources/___MODULE_NAME___
      echo "✅ モジュールを作成しました: ___PACKAGE_PATH___/Sources/___MODULE_NAME___/"
  - if: ___CREATE_TESTS___
    run: |
      set -e
      mv ___MODULE_NAME___Tests.swift ___PACKAGE_PATH___/Tests/___MODULE_NAME___Tests
      echo "✅ テストを作成しました: ___PACKAGE_PATH___/Tests/___MODULE_NAME___Tests/"
