@testable import EggKit
import FileManagerProtocol
import Foundation
import ProcessRunning
import Testing

@Suite("Preview transactions run lifecycle hooks in a sandboxed staging area")
struct AgentHatchPreviewTests {
    private let fileManager: some FileManagerProtocol = FileManager.default

    @Test("Rejects sandbox allowed paths unless sandbox is disabled")
    func rejectsSandboxAllowedPathsUnlessSandboxIsDisabled() async throws {
        let workspace = try makeWorkspace()
        defer { try? fileManager.removeItem(at: workspace.root) }

        await #expect(throws: LifecycleStepError.sandboxPermissionRequired(paths: ["/tmp/egg-preview-test"])) {
            try await makeRunner(workspace: workspace, sandboxDisabled: false).preview()
        }
    }

    @Test("Allows preview sandbox bypass when explicitly disabled")
    func allowsPreviewSandboxBypassWhenExplicitlyDisabled() async throws {
        let workspace = try makeWorkspace()
        defer { try? fileManager.removeItem(at: workspace.root) }

        let result = try await makeRunner(workspace: workspace, sandboxDisabled: true).preview()

        #expect(result.templateName == "PreviewTemplate")
        #expect(result.changes.contains { $0.path == "Generated.txt" && $0.kind == "add" })
    }

    private func makeWorkspace() throws -> Workspace {
        let root = try fileManager.makeTemporaryDirectory(prefix: "AgentHatchPreviewTests")
        let workingDirectory = root.appending(path: "work")
        let homeDirectory = root.appending(path: "home")
        let templateDirectory = root.appending(path: "template")
        try fileManager.createDirectory(at: workingDirectory, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: homeDirectory, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: templateDirectory, withIntermediateDirectories: true)
        try initializeGitRepository(at: workingDirectory)
        try fileManager.writeText("Generated by preview\n", at: templateDirectory.appending(path: "Generated.txt"))
        return Workspace(
            root: root,
            workingDirectory: workingDirectory,
            homeDirectory: homeDirectory,
            templateDirectory: templateDirectory,
        )
    }

    private func makeRunner(workspace: Workspace, sandboxDisabled: Bool) -> AgentHatchTransactionRunner {
        AgentHatchTransactionRunner(
            processRunner: ProcessRunner(),
            fileManager: fileManager,
            workingDirectory: workspace.workingDirectory,
            homeDirectory: workspace.homeDirectory,
            templateDirectory: workspace.templateDirectory,
            config: Config(
                name: "PreviewTemplate",
                description: "Preview template",
                sandbox: .init(allowedPaths: ["/tmp/egg-preview-test"]),
                hatch: .init(output: "."),
            ),
            parsedMacros: [],
            sandboxDisabled: sandboxDisabled,
        )
    }

    private func initializeGitRepository(at directory: URL) throws {
        let process = Process()
        process.executableURL = URL(filePath: "/usr/bin/git")
        process.arguments = ["init", "--quiet"]
        process.currentDirectoryURL = directory
        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            throw GitInitializationError.failed(status: process.terminationStatus)
        }
    }

    private struct Workspace {
        let root: URL
        let workingDirectory: URL
        let homeDirectory: URL
        let templateDirectory: URL
    }

    private enum GitInitializationError: Error {
        case failed(status: Int32)
    }
}
