@testable import EggKit
import FileManagerProtocol
import Foundation
import ProcessRunning
import Testing

@Suite("GitStagingChangeDetector diffs a working tree against a recorded baseline, honoring .gitignore and egg's own structural exclusions")
struct GitStagingChangeDetectorTests {
    private func makeWorkspace(prefix: String) throws -> (URL, any FileManagerProtocol) {
        let fileManager: some FileManagerProtocol = FileManager.default
        let root = try fileManager.makeTemporaryDirectory(prefix: prefix)
        return (root, fileManager)
    }

    private func detector(_ fileManager: any FileManagerProtocol) -> GitStagingChangeDetector {
        GitStagingChangeDetector(processRunner: ProcessRunner(), fileManager: fileManager)
    }

    @Test("classifies a new file as added, an edited file as modified, and a removed file as deleted relative to the recorded baseline")
    func reportsAddedModifiedAndDeletedFilesAgainstTheBaseline() async throws {
        let (root, fileManager) = try makeWorkspace(prefix: "GitStagingBasic")
        defer { try? fileManager.removeItem(at: root) }

        try fileManager.writeText("original\n", at: root.appending(path: "keep.txt"))
        try fileManager.writeText("remove me\n", at: root.appending(path: "gone.txt"))

        let detector = detector(fileManager)
        try await detector.recordBaseline(in: root)

        try fileManager.writeText("changed\n", at: root.appending(path: "keep.txt"))
        try fileManager.removeItem(at: root.appending(path: "gone.txt"))
        try fileManager.writeText("brand new\n", at: root.appending(path: "added.txt"))

        let summary = try await detector.changes(in: root)
        #expect(summary.added == ["added.txt"])
        #expect(summary.modified == ["keep.txt"])
        #expect(summary.deleted == ["gone.txt"])
    }

    @Test("excludes paths matched by the project's .gitignore (e.g. a generated node_modules directory) from the reported change set")
    func filesIgnoredByTheProjectSGitignoreAreNotReportedAsChanges() async throws {
        let (root, fileManager) = try makeWorkspace(prefix: "GitStagingIgnored")
        defer { try? fileManager.removeItem(at: root) }

        // The project's own .gitignore is the single source of truth — no
        // hardcoded denylist. node_modules generated by a script must not leak.
        try fileManager.writeText("node_modules/\n.build/\n", at: root.appending(path: ".gitignore"))
        try fileManager.writeText("print()\n", at: root.appending(path: "main.swift"))

        let detector = detector(fileManager)
        try await detector.recordBaseline(in: root)

        let nodeModules = root.appending(path: "node_modules")
        try fileManager.createDirectory(at: nodeModules, withIntermediateDirectories: true)
        try fileManager.writeText("junk\n", at: nodeModules.appending(path: "lib.js"))
        try fileManager.writeText("changed\n", at: root.appending(path: "main.swift"))

        let summary = try await detector.changes(in: root)
        #expect(summary.modified == ["main.swift"])
        #expect(summary.added.isEmpty)
        #expect(!summary.allPaths.contains { $0.hasPrefix("node_modules") })
    }

    @Test("PathFilter's include list overrides .gitignore so an explicitly included path is still reported as added")
    func includeForcesANormallyIgnoredPathIntoTheChangeSet() async throws {
        let (root, fileManager) = try makeWorkspace(prefix: "GitStagingInclude")
        defer { try? fileManager.removeItem(at: root) }

        try fileManager.writeText("dist/\n", at: root.appending(path: ".gitignore"))

        let detector = detector(fileManager)
        let filter = GitStagingChangeDetector.PathFilter(include: ["dist/bundle.js"])
        try await detector.recordBaseline(in: root, filter: filter)

        let dist = root.appending(path: "dist")
        try fileManager.createDirectory(at: dist, withIntermediateDirectories: true)
        try fileManager.writeText("bundle\n", at: dist.appending(path: "bundle.js"))

        let summary = try await detector.changes(in: root, filter: filter)
        #expect(summary.added == ["dist/bundle.js"])
    }

    @Test("never reports changes under .egg/transactions, since egg's own state directory is excluded structurally regardless of .gitignore")
    func eggSOwnEggDirectoryIsExcludedStructurally() async throws {
        let (root, fileManager) = try makeWorkspace(prefix: "GitStagingEgg")
        defer { try? fileManager.removeItem(at: root) }

        let detector = detector(fileManager)
        try await detector.recordBaseline(in: root)

        let eggDir = root.appending(path: ".egg/transactions")
        try fileManager.createDirectory(at: eggDir, withIntermediateDirectories: true)
        try fileManager.writeText("state\n", at: eggDir.appending(path: "tx.json"))

        let summary = try await detector.changes(in: root)
        #expect(summary.allPaths.isEmpty)
    }
}
