name: fo
description: fofofo
macros:
- name: ___FILE_NAME___
  description: The name of the file to be generated
  type: string
- name: ___OUTPUT___
  description: Template output directory where generated files will be placed
  type: path
hatch:
  output: ___OUTPUT___
