name: fuge
description: This is hogehogehoerogiaeor@ga@orega@iehaiorhgaioerhgoiaehrgioaherogiha@oerhigaioehrg@aiehrg@oahergaer@iogha@ergo@aehrg@oahgr@ae@ohirg@aoehrg@aohrg@oeahga@eohirg@oaehirg@eoahg@ohrega@oeirhgoaeihr@goiha@oerihg@oaiherg@oiharg

# Define custom macros that can be used throughout your template files and in this config file.
# Macros defined here can be referenced in file names, folder names, file contents, and
# within this config.yaml (e.g., in pre_hatch, hatch, post_hatch sections) using the format
# ___MACRO_NAME___. When you run 'egg hatch', you'll be prompted to provide values for these
# macros, which will then replace all occurrences in your template and configuration.
macros:
  - name: ___FILE_NAME___
    description: The name of the file to be generated
    type: string
  - name: ___OUTPUT___
    description: Template output directory where generated files will be placed
    type: path

#  - name: ___CREATE_TESTS___
#    description: Whether to create test files
#    type: boolean
#    default: false

# pre_hatch:
#  - id: setup-dirs
#    run: |
#      echo "test-dir=___OUTPUT___/Tests"
#  - if: ___CREATE_TESTS___
#    run: mkdir -p ${{ pre_hatch.setup-dirs.outputs.test-dir }}
hatch:
  output: ___OUTPUT___

# post_hatch:
#  - if: ___CREATE_TESTS___
#    run: swift package resolve