import Foundation
import Yams
import FileSystem
import Path

struct TemplateCreator {
    let fileSystem: any FileSysteming
    let encoder: YAMLEncoder = .defaultEncoder()
    let skipConfig: Bool
    let templateLocating: any TemplateLocating

    init(
        skipConfig: Bool,
        templateLocating: some TemplateLocating,
        fileSystem: some FileSysteming
    ) {
        self.fileSystem = fileSystem
        self.skipConfig = skipConfig
        self.templateLocating = templateLocating
    }

    func create(_ name: String, in locationType: TemplateLocationType) async throws {
        let templateDir = templateLocating.template(name, type: locationType)

        var createdPaths: [AbsolutePath] = []
        var directoryCreated = false

        do {
            try await fileSystem.makeDirectory(at: templateDir, options: [.createTargetParentDirectories])
            directoryCreated = true

            let filePath = try await createDefaultFile(templateDir)
            createdPaths.append(filePath)

            let configPath = try await createDefaultConfig(templateDir)
            createdPaths.append(configPath)
        } catch {
            // Rollback: delete all created files and directory on failure
            for path in createdPaths.reversed() {
                try? await fileSystem.remove(path)
            }
            if directoryCreated {
                try? await fileSystem.remove(templateDir)
            }
            throw error
        }
    }

    private func createDefaultConfig(_ templateDir: AbsolutePath) async throws -> AbsolutePath {
        let defaultConfigPath = templateDir.appending(component: "config.yaml")
        let defaultConfig = Config(
            postUseHook: """
            # This file can be deleted if not needed.
            # Write commands to be executed after template files/folders are generated by the 'use' command.
            # You can use macros here: ___FILE_NAME___, ___DATE___, ___DATE(yyyyMMdd)___, ___SYSTEM-USER___
            echo "Hello World!"
            """
        )
        try await fileSystem.writeAsYAML(defaultConfig, at: defaultConfigPath, encoder: encoder)
        return defaultConfigPath
    }

    private func createDefaultFile(_ templateDir: AbsolutePath) async throws -> AbsolutePath {
        let defaultFilePath = templateDir.appending(component: "___FILE_NAME___View.swift")
        let defaultFileContent = """
        // Available default macros:
        //   - ___DATE___: Current date in default format
        //   - ___DATE(yyyyMMdd)___: Current date in custom format
        //   - ___SYSTEM_USER___: System username
        //
        // You can also define custom macros (e.g., ___USER_DEFINED___, ___FILE_NAME___) and provide values via:
        //   - Command line: egg use <template-name> --user-defined foo --file-name bar
        //   - Interactive prompt: will be asked during 'egg use' command

        struct ___FILE_NAME___View: View {
            var body: some View {
                Text("___FILE_NAME___View")
            }
        }
        """
        try await fileSystem.writeText(defaultFileContent, at: defaultFilePath)
        return defaultFilePath
    }
}
